name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: hbcl-Linux-64bit.zip
          - os: windows-latest
            artifact_name: hbcl-Windows-64bit.zip
          - os: macos-latest
            artifact_name: hbcl-Darwin-64bit.zip

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install poetry
        run: python -m pip install poetry pyinstaller cchardet chardet pprp

      - name: Build project using pyinstaller
        run: python build.py

      - name: Create release to github according to tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
