name: CD

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Update dependencies according to the manifest
        run: poetry update

      - name: Build project
        run: poetry build

      - name: Create release to github according to tag
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/heybrochecklog*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true