name: CD

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
          
      - name: Install poetry
        run: python -m pip install poetry
        
      - name: Resolve dependencies
        run: python -m poetry install
        
      - name: Build project
        run: python -m poetry build
        
      - name: Create release artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: hbcl-release
          path: dist/*.*
          retention-days: 30
